### ISSUE TITLE
CPPCHECK report

### ISSUE THREAD

**Issue by surendra060** [bayotop/tls-parser#6]
CPPCHECK  is not able to differentiate if it is a redundant usage or there is a chance of NULL pointer dereference (Since “stream”, theoretically can contain NULL pointer. Hence,  if(stream!=NULL)  is a better construct to be used.  Also, the tool gives one Style check error at two instances for usage of  “asctime”. Usage of  “strftime” is recommended.

**Comment by bayotop** [comment]
This issue was partially fixed in https://github.com/bayotop/tls-parser/commit/9b11f65442fb5c3b94d9e07f4a7ebfba428f8b0a. 

The "asctime" still has to be done.
